apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: dc-is
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: openshift/hello-openshift
    from:
      kind: DockerImage
      name: openshift/hello-openshift
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
